spring:
  security:
    saml2:
      relyingparty:
        registration:
          idp:
            identityprovider:
              entity-id: ${IDP_ID:http://localhost:9080}
              metadata-uri: ${IDP_METADATA_URL:http://localhost:9080/metadata}
              singlesignon:
                sign-request: false

management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /
  endpoint:
    health:
      enabled: true

server:
  port: ${PORT:8080}
  forward-headers-strategy: native

custom:
  login-redirect-url: ${LOGIN_REDIRECT_URL:http://localhost:8080/}
