custom:
  data-dir: ${DATA-DIR:.}/config
  config-file: ${custom.data-dir}/saml-proxy.yaml
  idp-metadata-location: file:${custom.data-dir}/idp-metadata.xml

spring:
  config:
    import: "file:${custom.config-file}"
  cloud:
    compatibility-verifier:
      enabled: false
    config:
      import-check:
        enabled: false
  web:
    resources:
      static-locations: ${WEB_RESOURCES_PATH:classpath:/static}
      chain:
        cache: ${WEB_RESOURCES_CACHE:true}
  thymeleaf:
    cache: ${TEMPLATE_CACHE:true}
    prefix: ${TEMPLATE_PATH:classpath:/templates/}

management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /
      exposure:
        include: health,logfile
  endpoint:
    health:
      enabled: true
    logfile:
      enabled: true

logging:
  file:
    name: ${LOG_FILE:./logs/saml-proxy.log}
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7
      total-size-cap: 200MB

server:
  port: ${PORT:8080}
  forward-headers-strategy: native
