custom:
  data-dir: ${DATA-DIR:${user.dir}}
  config-file: ${custom.data-dir}/saml-proxy.yaml

spring:
  config:
    import: "optional:file:${custom.config-file}"
  cloud:
    config:
      import-check:
        enabled: false
  web:
    resources:
      static-locations: ${WEB_RESOURCES_PATH:classpath:/static}
      chain:
        cache: ${WEB_RESOURCES_CACHE:true}
  thymeleaf:
    cache: ${TEMPLATE_CACHE:true}
    prefix: ${TEMPLATE_PATH:classpath:/templates/}

management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /
  endpoint:
    health:
      enabled: true

server:
  port: ${PORT:8080}
  forward-headers-strategy: native
