custom:
  data-dir: ${DATA-DIRF:${user.dir}}

spring:
  config:
    import: "optional:file:${custom.data-dir}/saml-proxy.yaml"
  cloud:
    config:
      import-check:
        enabled: false
  thymeleaf:
    prefix: classpath:/templates/

management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /
  endpoint:
    health:
      enabled: true

server:
  port: ${PORT:8080}
  forward-headers-strategy: native
