spring:
  security:
    saml2:
      relyingparty:
        registration:
          idp:
            identityprovider:
              metadata-uri: "classpath:default-idp-metadata.xml"
              singlesignon:
                sign-request: false
            entity-id: "{baseUrl}/saml2/service-provider-metadata/idp"

logging:
  level:
    root: INFO

custom:
  admin:
    username: ${ADMIN_USERNAME}
    password: ${ADMIN_PASSWORD}
  login-redirect-url: ${LOGIN_REDIRECT_URL}
