spring:
  security:
    saml2:
      relyingparty:
        registration:
          idp:
            identityprovider:
              entity-id: http://www.okta.com/exk2mr5bm7QMy4sgi5d7
              metadata-uri: "classpath:default-idp-metadata.xml"
              singlesignon:
                sign-request: false
            entity-id: "{baseUrl}/saml2/service-provider-metadata/idp"

logging:
  level:
    root: INFO

custom:
  admin:
    username: ${ADMIN_USERNAME}
    password: ${ADMIN_PASSWORD}
  login-redirect-url: ${LOGIN_REDIRECT_URL}
