name: deploy

on:
  push:
    branches:
      - main
      - test

env:
  AWS_REGION: eu-central-1
  APP_NAME: ${{ github.event.repository.name }}
  JAR_PATH: target/saml-proxy-0.0.1-SNAPSHOT.jar
  APP_PORT: 8080
  AWS_PLATFORM: corretto-11
  BASE_DOMAIN: saml-proxy.dmitrytest.site
  IDP_ID: http://www.okta.com/exk2ma247fNw301Mp5d7
  IDP_METADATA_URL: https://dev-36942153.okta.com/app/exk2ma247fNw301Mp5d7/sso/saml/metadata
  LOGIN_REDIRECT_URL: https://google.com

jobs:
  deploy-aws:
    runs-on: ubuntu-latest

    steps:
      - uses: rlespinasse/github-slug-action@v3.x

      - name: set environment variables
        run: |
          echo "EB_ENVIRONMENT=${{ env.GITHUB_REF_SLUG }}" >> $GITHUB_ENV

      - run: |
          echo "${{secrets.SERVICE_ACCOUNT}}" > 1.json
          ls -la
          cat 1.json
